### ISSUE TITLE
INSTALLED_APPS.append raises AppRegistryNotReady

### ISSUE THREAD

**Issue by fleonasb** [ajostergaard/django-payments-redsys#2]
Django v1.11.17
Wagtail v2.3
Python 3.6

Added PAYMENT_VARIANTS into base.py (Wagtail splits Django settings between different files):
```python
PAYMENT_VARIANTS = {
    'redsys': ('payments_redsys.RedsysProvider', {
        'merchant_code': 'mycode',
        'terminal': '1',
        'shared_secret': 'qwertyasdf0123456789',
    })
}

CHECKOUT_PAYMENT_CHOICES = [('redsys', 'Redsys')]
```

Adding:

```python
if any('redsys' in provider for provider in CHECKOUT_PAYMENT_CHOICES):
    INSTALLED_APPS.append('payments_redsys')
```

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fd7e056c0d0>
Traceback (most recent call last):
  File "/home/fleon/.virtualenvs/virmyasb/lib/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/fleon/.virtualenvs/virmyasb/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    autoreload.raise_last_exception()
  File "/home/fleon/.virtualenvs/virmyasb/lib/python3.6/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/home/fleon/.virtualenvs/virmyasb/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/fleon/.virtualenvs/virmyasb/lib/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/fleon/.virtualenvs/virmyasb/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/fleon/.virtualenvs/virmyasb/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/fleon/.virtualenvs/virmyasb/lib/python3.6/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/home/fleon/.virtualenvs/virmyasb/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/fleon/.virtualenvs/virmyasb/lib/python3.6/site-packages/payments_redsys/__init__.py", line 38, in <module>
    from payments.forms import PaymentForm
  File "/home/fleon/.virtualenvs/virmyasb/lib/python3.6/site-packages/payments/forms.py", line 11, in <module>
    from .fields import (CreditCardNumberField, CreditCardExpiryField,
  File "/home/fleon/.virtualenvs/virmyasb/lib/python3.6/site-packages/payments/fields.py", line 10, in <module>
    from .core import get_credit_card_issuer
  File "/home/fleon/.virtualenvs/virmyasb/lib/python3.6/site-packages/payments/core.py", line 20, in <module>
    from django.contrib.sites.models import Site
  File "/home/fleon/.virtualenvs/virmyasb/lib/python3.6/site-packages/django/contrib/sites/models.py", line 84, in <module>
    class Site(models.Model):
  File "/home/fleon/.virtualenvs/virmyasb/lib/python3.6/site-packages/django/db/models/base.py", line 110, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/fleon/.virtualenvs/virmyasb/lib/python3.6/site-packages/django/apps/registry.py", line 247, in get_containing_app_config
    self.check_apps_ready()
  File "/home/fleon/.virtualenvs/virmyasb/lib/python3.6/site-packages/django/apps/registry.py", line 125, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by ajostergaard** [comment]
Looks to me like a django_payments or Wagtail issue. Have you tried any other django_payments plugins?
